import { writeFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { redirects } from '../src/data/redirects';
import { wpGeneratedRedirects } from '../src/data/redirects-wp-gen';

const BLOG_DIR = path.resolve('content/blog');

function blogPostRedirects(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const file of readdirSync(BLOG_DIR)) {
    if (!file.endsWith('.md')) continue;
    const slug = file.replace(/\.md$/, '');
    out[`/${slug}`] = `/blog/${slug}`;
  }
  return out;
}

function ensureTrailingSlash(p: string): string {
  if (p === '/' || p.endsWith('/')) return p;
  const last = p.slice(p.lastIndexOf('/') + 1);
  if (last.includes('.')) return p;
  return p + '/';
}

function stripTrailingSlash(p: string): string {
  if (p === '/' || !p.endsWith('/')) return p;
  return p.slice(0, -1);
}

// Manual redirects win over auto-generated.
const merged: Record<string, string> = {
  ...blogPostRedirects(),
  ...wpGeneratedRedirects,
  ...redirects,
};

// Keys: normalized to no trailing slash (middleware strips before lookup).
// Values: normalized to trailing slash (canonical destination).
const normalized: Record<string, string> = {};
for (const [from, to] of Object.entries(merged)) {
  normalized[stripTrailingSlash(from)] = ensureTrailingSlash(to);
}

const sortedEntries = Object.entries(normalized).sort(([a], [b]) => a.localeCompare(b));
const mapLines = [
  '// AUTO-GENERATED by scripts/build-redirects.ts. Do not edit by hand.',
  '// Consumed by functions/_middleware.ts for single-hop legacy redirects.',
  '',
  'export const legacyRedirects: Record<string, string> = {',
  ...sortedEntries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
  '};',
  '',
];
writeFileSync('src/data/redirects-generated.ts', mapLines.join('\n'));

const redirectsFileLines = [
  '# Generated by scripts/build-redirects.ts. Do not edit by hand.',
  '# Legacy redirects and trailing-slash enforcement live in functions/_middleware.ts.',
  '',
  '# SPA fallback',
  '/* /index.html 200',
  '',
];
writeFileSync('public/_redirects', redirectsFileLines.join('\n'));

console.log(
  `Wrote ${sortedEntries.length} legacy redirects to src/data/redirects-generated.ts and SPA fallback to public/_redirects`,
);
